import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <NextIntlClientProvider messages={await getMessages()}>
        <body className={inter.className}>
          <AppRouterCacheProvider>
            {children}
          </AppRouterCacheProvider>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}

export const dynamic = "force-dynamic";